const moment = require('moment');

module.exports = [
    {
        code: "SOC",
        image: "sign-of-the-cross.jpg",
        crucifix: true,
        title: "SIGN OF THE CROSS",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "AC",
        image: "sign-of-the-cross-2.jpg",
        crucifix: true,
        title: "APOSTLES' CREED",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "OF-O",
        image: "our-father-2.jpg",
        crucifix: false,
        title: "OUR FATHER",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "HM-F",
        image: "glory-be.jpg",
        crucifix: false,
        title: "HAIL MARY\n Faith",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "HM-H",
        image: "glorious-4-assumption.jpg",
        crucifix: false,
        title: "HAIL MARY\n Hope",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "HM-C",
        image: "glorious-5-queen.jpg",
        crucifix: false,
        title: "HAIL MARY\n Charity",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "GB",
        image: "glory-be-2.jpg",
        crucifix: false,
        title: "GLORY BE",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "FATIMA",
        image: "children-of-fatima.jpg",
        crucifix: false,
        title: "FATIMA PRAYER",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "HHQ",
        image: "marian-image-2.jpg",
        crucifix: false,
        title: "HAIL HOLY QUEEN",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "EP",
        image: "holy-trinity.jpg",
        crucifix: false,
        title: "ENDING PRAYER",
        subtitle: "",
        subtitle_2_1: "",
        subtitle_2_2: "",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "1M-G",
        image: "glorious-1-resurrection.jpg",
        crucifix: false,
        title: "GLORIOUS MYSTERIES",
        subtitle: "1",
        subtitle_2_1: "The Resurrection",
        subtitle_2_2: "Fruit: Faith",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "2M-G",
        image: "glorious-2-ascension.jpg",
        crucifix: false,
        title: "GLORIOUS MYSTERIES",
        subtitle: "2",
        subtitle_2_1: "The Ascension",
        subtitle_2_2: "Fruit: Hope, Desire for Heaven",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "3M-G",
        image: "glorious-3-holy spirit.jpg",
        crucifix: false,
        title: "GLORIOUS MYSTERIES",
        subtitle: "3",
        subtitle_2_1: "The Descent of the Holy Spirit",
        subtitle_2_2: "Fruit: Wisdom and Love of God",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "4M-G",
        image: "glorious-4-assumption.jpg",
        crucifix: false,
        title: "GLORIOUS MYSTERIES",
        subtitle: "4",
        subtitle_2_1: "The Assumption of Mary",
        subtitle_2_2: "Fruit: Devotion to Mary",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "5M-G",
        image: "glorious-5-queen.jpg",
        crucifix: false,
        title: "GLORIOUS MYSTERIES",
        subtitle: "5",
        subtitle_2_1: "The Coronation of Mary",
        subtitle_2_2: "Fruit: Eternal Happiness",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "1M-J",
        image: "joyful-1-annunciation.jpg",
        crucifix: false,
        title: "JOYFUL MYSTERIES",
        subtitle: "1",
        subtitle_2_1: "The Annunciation",
        subtitle_2_2: "Fruit: Humility",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "2M-J",
        image: "joyful-2-visitation.jpg",
        crucifix: false,
        title: "JOYFUL MYSTERIES",
        subtitle: "2",
        subtitle_2_1: "The Visitation",
        subtitle_2_2: "Fruit: Love of Neighbor",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "3M-J",
        image: "joyful-3-nativity.jpg",
        crucifix: false,
        title: "JOYFUL MYSTERIES",
        subtitle: "3",
        subtitle_2_1: "The Nativity",
        subtitle_2_2: "Fruit: Poverty of Spirit",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "4M-J",
        image: "joyful-4-presentation.jpg",
        crucifix: false,
        title: "JOYFUL MYSTERIES",
        subtitle: "4",
        subtitle_2_1: "The Presentation",
        subtitle_2_2: "Fruit: Obedience",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "5M-J",
        image: "joyful-5-temple.jpg",
        crucifix: false,
        title: "JOYFUL MYSTERIES",
        subtitle: "5",
        subtitle_2_1: "The Finding in the Temple",
        subtitle_2_2: "Fruit: Piety",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "1M-S",
        image: "sorrowful-1-agony.jpg",
        crucifix: false,
        title: "SORROWFUL MYSTERIES",
        subtitle: "1",
        subtitle_2_1: "The Agony in the Garden",
        subtitle_2_2: "Fruit: Conformity to the will of God",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "2M-S",
        image: "sorrowful-2-scourging.jpg",
        crucifix: false,
        title: "SORROWFUL MYSTERIES",
        subtitle: "2",
        subtitle_2_1: "The Scourging at the Pillar",
        subtitle_2_2: "Fruit: Purity and Mortification",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "3M-S",
        image: "sorrowful-3-crowning.jpg",
        crucifix: false,
        title: "SORROWFUL MYSTERIES",
        subtitle: "3",
        subtitle_2_1: "The Crowning with Thorns",
        subtitle_2_2: "Fruit: Moral Courage",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "4M-S",
        image: "sorrowful-4-carrying.jpg",
        crucifix: false,
        title: "SORROWFUL MYSTERIES",
        subtitle: "4",
        subtitle_2_1: "The Carrying of the Cross",
        subtitle_2_2: "Fruit: Patience",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "5M-S",
        image: "sorrowful-5-crucifixtion.jpg",
        crucifix: false,
        title: "SORROWFUL MYSTERIES",
        subtitle: "5",
        subtitle_2_1: "The Crucifixion",
        subtitle_2_2: "Fruit: Salvation",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "1M-L",
        image: "luminous-1-baptism.jpg",
        crucifix: false,
        title: "LUMINOUS MYSTERIES",
        subtitle: "1",
        subtitle_2_1: "The Baptism in the Jordan",
        subtitle_2_2: "Fruit: Openess to the Holy Spirit",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "2M-L",
        image: "luminous-2-cana.jpg",
        crucifix: false,
        title: "LUMINOUS MYSTERIES",
        subtitle: "2",
        subtitle_2_1: "The Wedding Feast at Cana",
        subtitle_2_2: "Fruit: To Jesus through Mary",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "3M-L",
        image: "luminous-3-proclamation.jpg",
        crucifix: false,
        title: "LUMINOUS MYSTERIES",
        subtitle: "3",
        subtitle_2_1: "Proclamation of the Kingdom of God",
        subtitle_2_2: "Fruit: Repentance, Trust in God",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "4M-L",
        image: "luminous-4-transfiguration.jpg",
        crucifix: false,
        title: "LUMINOUS MYSTERIES",
        subtitle: "4",
        subtitle_2_1: "The Transfiguration of Jesus",
        subtitle_2_2: "Fruit: Desire for Holiness",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "5M-L",
        image: "luminous-5-eucharist.jpg",
        crucifix: false,
        title: "LUMINOUS MYSTERIES",
        subtitle: "5",
        subtitle_2_1: "The Institution of the Eucharist",
        subtitle_2_2: "Fruit: Eucharistic Adoration",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    }
]