const moment = require('moment');

module.exports = [
    {
        code: "JOYFUL-1",
        mystery_code: "JOYFUL",
        image: "joyful-detail-1.jpg",
        title: "The First Joyful Mystery",
        subtitle: "The Annunication",
        detail_1: "1. In the sixth month, the angel Gabriel was sent from God to a town of Galilee called Nazareth, to a virgin betrothed to a man named Joseph, of the house of David, and the virgin’s name was Mary. (Luke 1:26-27)",
        detail_2: "2. And coming to her, he said, “Hail, favored one! The Lord is with you.” (Luke 1:28)",
        detail_3: "3. But she was greatly troubled at what was said and pondered what sort of greeting this might be. Then the angel said to her, “Do not be afraid, Mary, for you have found favor with God.” (Luke 1:29-30)",
        detail_4: "4. “Behold, you will conceive in your womb and bear a son, and you shall name him Jesus.” (Luke 1:31)",
        detail_5: "5. “He will be great and will be called Son of the Most High, and the Lord God will give him the throne of David his father, and he will rule over the house of Jacob forever, and of his kingdom there will be no end.” (Luke 1:32-33)",
        detail_6: "6. But Mary said to the angel, “How can this be, since I have no relations with a man?” (Luke 1:34)",
        detail_7: "7. And the angel said to her in reply, “The holy Spirit will come upon you, and the power of the Most High will overshadow you. Therefore the child to be born will be called holy, the Son of God.” (Luke 1:35)",
        detail_8: "8. “And behold, Elizabeth, your relative, has also conceived a son in her old age, and this is the sixth month for her who was called barren; for nothing will be impossible for God.” (Luke 1:36-37)",
        detail_9: "9. Mary said, “Behold, I am the handmaid of the Lord. May it be done to me according to your word.” Then the angel departed from her. (Luke 1:38)",
        detail_10: "10. And the Word became flesh and made his dwelling among us, and we saw his glory, the glory as of the Father’s only Son, full of grace and truth. (John 1:14)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-2",
        mystery_code: "JOYFUL",
        image: "joyful-detail-2.jpg",
        title: "The Second Joyful Mystery",
        subtitle: "The Visitation",
        detail_1: "1. During those days Mary set out and traveled to the hill country in haste to a town of Judah, where she entered the house of Zechariah and greeted Elizabeth. (Luke 1:39-40)",
        detail_2: "2. When Elizabeth heard Mary’s greeting, the infant leaped in her womb, and Elizabeth, filled with the holy Spirit, cried out in a loud voice and said, “Most blessed are you among women, and blessed is the fruit of your womb.” (Luke 1:41-42)",
        detail_3: "3. “And how does this happen to me, that the mother of my Lord should come to me? For at the moment the sound of your greeting reached my ears, the infant in my womb leaped for joy.” (Luke 1:43-44)",
        detail_4: "4. Blessed are you who believed that what was spoken to you by the Lord would be fulfilled.” (Luke 1:45)",
        detail_5: "5. And Mary said: “My soul proclaims the greatness of the Lord; my spirit rejoices in God my savior.” (Luke 1:46-47)",
        detail_6: "6. “For he has looked upon his handmaid’s lowliness; behold, from now on will all ages call me blessed.” (Luke 1:48)",
        detail_7: "7. “The Mighty One has done great things for me, and holy is his name. His mercy is from age to age to those who fear him.” (Luke 1:49-50)",
        detail_8: "8. “He has shown might with his arm, dispersed the arrogant of mind and heart. He has thrown down the rulers from their thrones but lifted up the lowly.” (Luke 1:51-52)",
        detail_9: "9. “The hungry he has filled with good things; the rich he has sent away empty. He has helped Israel his servant, remembering his mercy, according to his promise to our fathers, to Abraham and to his descendants forever.” (Luke 1:53-55)",
        detail_10: "10. Mary remained with her about three months and then returned to her home. (Luke 1:56)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-3",
        mystery_code: "JOYFUL",
        image: "joyful-detail-3.jpg",
        title: "The Third Joyful Mystery",
        subtitle: "The Nativity",
        detail_1: "1. Now this is how the birth of Jesus Christ came about. When his mother Mary was betrothed to Joseph, but before they lived together, she was found with child through the holy Spirit. (Matthew 1:18)",
        detail_2: "2. Joseph her husband, since he was a righteous man, yet unwilling to expose her to shame, decided to divorce her quietly. (Matthew 1:19)",
        detail_3: "3. Such was his intention when, behold, the angel of the Lord appeared to him in a dream and said, “Joseph, son of David, do not be afraid to take Mary your wife into your home. For it is through the holy Spirit that this child has been conceived in her. She will bear a son and you are to name him Jesus, because he will save his people from their sins.” (Matthew 1:20-21)",
        detail_4: "4. In those days a decree went out from Caesar Augustus that the whole world should be enrolled. So all went to be enrolled, each to his own town. And Joseph too went up from Galilee from the town of Nazareth to Judea, to the city of David that is called Bethlehem, because he was of the house and family of David, to be enrolled with Mary, his betrothed, who was with child. (Luke 2:1, 3-5)",
        detail_5: "5. While they were there, the time came for her to have her child, and she gave birth to her firstborn son. She wrapped him in swaddling clothes and laid him in a manger, because there was no room for them in the inn. (Luke 2:6-7)",
        detail_6: "6. Now there were shepherds in that region living in the fields and keeping the night watch over their flock. The angel of the Lord appeared to them and the glory of the Lord shone around them, and they were struck with great fear. (Luke 2:8-9)",
        detail_7: "7. The angel said to them, “Do not be afraid; for behold, I proclaim to you good news of great joy that will be for all the people. (Luke 2:10)",
        detail_8: "8. For today in the city of David a savior has been born for you who is Messiah and Lord. (Luke 2:11)",
        detail_9: "9. And this will be a sign for you: you will find an infant wrapped in swaddling clothes and lying in a manger.” (Luke 2:12)",
        detail_10: "10. And suddenly there was a multitude of the heavenly host with the angel, praising God and saying:  “Glory to God in the highest and on earth peace to those on whom his favor rests.” (Luke 2:13-14)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-4",
        mystery_code: "JOYFUL",
        image: "joyful-detail-4.jpg",
        title: "The Fourth Joyful Mystery",
        subtitle: "The Presentation",
        detail_1: "1. When the days were completed for their purification according to the law of Moses, they took him up to Jerusalem to present him to the Lord. (Luke 2:22)",
        detail_2: "2. Now there was a man in Jerusalem whose name was Simeon. This man was righteous and devout, awaiting the consolation of Israel, and the holy Spirit was upon him. (Luke 2:25)",
        detail_3: "3. It had been revealed to him by the holy Spirit that he should not see death before he had seen the Messiah of the Lord. (Luke 2:26)",
        detail_4: "4. He came in the Spirit into the temple; and when the parents brought in the child Jesus to perform the custom of the law in regard to him, he took him into his arms and blessed God. (Luke 2:27-28a) ",
        detail_5: "5. “Now, Master, you may let your servant go in peace, according to your word,” (Luke 2:29)",
        detail_6: "6. “For my eyes have seen your salvation, which you prepared in sight of all the peoples,” (Luke 2:30-31)",
        detail_7: "7. “A light for revelation to the Gentiles, and glory for your people Israel.” (Luke 2:32)",
        detail_8: "8. The child’s father and mother were amazed at what was said about him; and Simeon blessed them and said to Mary his mother, “Behold, this child is destined for the fall and rise of many in Israel, and to be a sign that will be contradicted (and you yourself a sword will pierce) so that the thoughts of many hearts may be revealed.” (Luke 2:33-35)",
        detail_9: "9. There was also a prophetess, Anna, the daughter of Phanuel, of the tribe of Asher. She was advanced in years, having lived seven years with her husband after her marriage, and then as a widow until she was eighty-four. She never left the temple, but worshiped night and day with fasting and prayer. (Luke 2:36-37)",
        detail_10: "10. And coming forward at that very time, she gave thanks to God and spoke about the child to all who were awaiting the redemption of Jerusalem. (Luke 2:38)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-5",
        mystery_code: "JOYFUL",
        image: "joyful-detail-5.jpg",
        title: "The Fifth Joyful Mystery",
        subtitle: "The Finding in the Temple",
        detail_1: "1. Each year his parents went to Jerusalem for the feast of Passover, and when he was twelve years old, they went up according to festival custom. (Luke 2:41-42)",
        detail_2: "2. After they had completed its days, as they were returning, the boy Jesus remained behind in Jerusalem, but his parents did not know it. (Luke 2:43)",
        detail_3: "3. Thinking that he was in the caravan, they journeyed for a day and looked for him among their relatives and acquaintances. (Luke 2:44)",
        detail_4: "4. But not finding him, they returned to Jerusalem to look for him. (Luke 2:45)",
        detail_5: "5. After three days they found him in the temple, sitting in the midst of the teachers, listening to them and asking them questions. (Luke 2:46)",
        detail_6: "6. And all who heard him were astounded at his understanding and his answers. (Luke 2:47)",
        detail_7: "7. When his parents saw him, they were astonished, and his mother said to him, “Son, why have you done this to us? Your father and I have been looking for you with great anxiety.” (Luke 2:48)",
        detail_8: "8. And he said to them, “Why were you looking for me? Did you not know that I must be in my Father’s house?” But they did not understand what he said to them. (Luke 2:49-50)",
        detail_9: "9. He went down with them and came to Nazareth, and was obedient to them; and his mother kept all these things in her heart. (Luke 2:51)",
        detail_10: "10. And Jesus advanced in wisdom and age and favor before God and man. (Luke 2:52)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    }
]
