const moment = require('moment');

module.exports = [
    {
        code: "GLORIOUS-1",
        mystery_code: "GLORIOUS",
        image: "glorious-detail-1.jpg",
        title: "The First Glorious Mystery",
        subtitle: "The Resurrection",
        detail_1: "1. After the sabbath, as the first day of the week was dawning, Mary Magdalene and the other Mary came to see the tomb. And behold, there was a great earthquake; for an angel of the Lord descended from heaven, approached, rolled back the stone, and sat upon it. (Matthew 28:1-2)",
        detail_2: "2. Then the angel said to the women in reply, “Do not be afraid! I know that you are seeking Jesus the crucified. He is not here, for he has been raised just as he said.” (Matthew 28:5-6a)",
        detail_3: "3. “Come and see the place where he lay. Then go quickly and tell his disciples, ‘He has been raised from the dead, and he is going before you to Galilee; there you will see him.’ Behold, I have told you.” (Matthew 28:6b-7)",
        detail_4: "4. Then they went away quickly from the tomb, fearful yet overjoyed, and ran to announce this to his disciples. (Matthew 28:8)",
        detail_5: "5. On the evening of that first day of the week, when the doors were locked, where the disciples were, for fear of the Jews, Jesus came and stood in their midst and said to them, “Peace be with you.” (John 20:19)",
        detail_6: "6. When he had said this, he showed them his hands and his side. The disciples rejoiced when they saw the Lord. (John 20:20)",
        detail_7: "7. Jesus said to them again, “Peace be with you. As the Father has sent me, so I send you.” (John 20:21)",
        detail_8: "8. And when he had said this, he breathed on them and said to them, “Receive the holy Spirit. Whose sins you forgive are forgiven them, and whose sins you retain are retained.” (John 20:22-23)",
        detail_9: "9. “Go, therefore, and make disciples of all nations, baptizing them in the name of the Father, and of the Son, and of the holy Spirit, teaching them to observe all that I have commanded you. (Matthew 28:19)",
        detail_10: "10. “And behold, I am with you always, until the end of the age.” (Matthew 28:20)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "GLORIOUS-2",
        mystery_code: "GLORIOUS",
        image: "glorious-detail-2.jpg",
        title: "The Second Glorious Mystery",
        subtitle: "The Ascension",
        detail_1: "1. “But now I am going to the one who sent me, and not one of you asks me, ‘Where are you going?’ But because I told you this, grief has filled your hearts.” (John 16:5-6)",
        detail_2: "2. “But I tell you the truth, it is better for you that I go. For if I do not go, the Advocate will not come to you. But if I go, I will send him to you.” (John 16:7)",
        detail_3: "3. Then he led them out as far as Bethany, raised his hands, and blessed them. (Luke 24:50)",
        detail_4: "4. When they had gathered together they asked him, “Lord, are you at this time going to restore the kingdom to Israel?” (Acts 1:6)",
        detail_5: "5. He answered them, “It is not for you to know the times or seasons that the Father has established by his own authority.” (Acts 1:7)",
        detail_6: "6. “But you will receive power when the holy Spirit comes upon you, and you will be my witnesses in Jerusalem, throughout Judea and Samaria, and to the ends of the earth.” (Acts 1:8)",
        detail_7: "7. When he had said this, as they were looking on, he was lifted up, and a cloud took him from their sight. (Acts 1:9)",
        detail_8: "8. So then the Lord Jesus, after he spoke to them, was taken up into heaven and took his seat at the right hand of God. (Mark 16:19)",
        detail_9: "9. While they were looking intently at the sky as he was going, suddenly two men dressed in white garments stood beside them. They said, “Men of Galilee, why are you standing there looking at the sky? This Jesus who has been taken up from you into heaven will return in the same way as you have seen him going into heaven.” (Acts 1:10-11)",
        detail_10: "10. They did him homage and then returned to Jerusalem with great joy, and they were continually in the temple praising God. (Luke 24:52-53)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "GLORIOUS-3",
        mystery_code: "GLORIOUS",
        image: "glorious-detail-3.jpg",
        title: "The Third Glorious Mystery",
        subtitle: "The Descent of the Holy Spirit",
        detail_1: "1. “And I will ask the Father, and he will give you another Advocate to be with you always, the Spirit of truth, which the world cannot accept, because it neither sees nor knows it. But you know it, because it remains with you, and will be in you.” (John 14:16-17)",
        detail_2: "2. When the time for Pentecost was fulfilled, they were all in one place together. (Acts 2:1)",
        detail_3: "3. And suddenly there came from the sky a noise like a strong driving wind, and it filled the entire house in which they were. (Acts 2:2)",
        detail_4: "4. Then there appeared to them tongues as of fire, which parted and came to rest on each one of them. (Acts 2:3)",
        detail_5: "5. And they were all filled with the holy Spirit and began to speak in different tongues, as the Spirit enabled them to proclaim. (Acts 2:4)",
        detail_6: "6. Now there were devout Jews from every nation under heaven staying in Jerusalem. At this sound, they gathered in a large crowd, but they were confused because each one heard them speaking in his own language. (Acts 2:5-6)",
        detail_7: "7. Then Peter stood up with the Eleven, raised his voice, and proclaimed to them, “You who are Jews, indeed all of you staying in Jerusalem. Let this be known to you, and listen to my words. These people are not drunk, as you suppose, for it is only nine o’clock in the morning.” (Acts 2:14-15)",
        detail_8: "8. “No, this is what was spoken through the prophet Joel: ‘It will come to pass in the last days,’ God says, ‘that I will pour out a portion of my spirit upon all flesh. Your sons and your daughters shall prophesy, your young men shall see visions, your old men shall dream dreams.’” (Acts 2:16-17)",
        detail_9: "9. “‘Indeed, upon my servants and my handmaids I will pour out a portion of my spirit in those days, and they shall prophesy.’” (Acts 2:18)",
        detail_10: "10. Peter said to them, “Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins; and you will receive the gift of the holy Spirit. … Those who accepted his message were baptized, and about three thousand persons were added that day. (Acts 2:38,41)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "GLORIOUS-4",
        mystery_code: "GLORIOUS",
        image: "glorious-detail-4.jpg",
        title: "The Fourth Glorious Mystery",
        subtitle: "The Assumption of the Blessed Virgin Mary",
        detail_1: "1. My lover speaks and says to me, “Arise, my friend, my beautiful one, and come!” (Song of Songs 2:10)",
        detail_2: "2. “For see, the winter is past, the rains are over and gone.” (Song of Songs 2:11)",
        detail_3: "3. “Do not let your hearts be troubled. You have faith in God; have faith also in me.” (John 14:1)",
        detail_4: "4. “In my Father’s house there are many dwelling places. If there were not, would I have told you that I am going to prepare a place for you?” (John 14:2)",
        detail_5: "5. “And if I go and prepare a place for you, I will come back again and take you to myself, so that where I am you also may be.” (John 14:3)",
        detail_6: "6. “Father, they are your gift to me. I wish that where I am they also may be with me, that they may see my glory that you gave me, because you loved me before the foundation of the world.” (John 17:24)",
        detail_7: "7. “Behold, I tell you a mystery. We shall not all fall asleep, but we will all be changed, in an instant, in the blink of an eye, at the last trumpet.” (1 Corinthians 15:51-52a)",
        detail_8: "8. “For the trumpet will sound, the dead will be raised incorruptible, and we shall be changed.” (1 Corinthians 15:52b)",
        detail_9: "9. “For that which is corruptible must clothe itself with incorruptibility, and that which is mortal must clothe itself with immortality.” (1 Corinthians 15:53)",
        detail_10: "10. “Death is swallowed up in victory. Where, O death, is your victory? Where, O death, is your sting?” (1 Corinthians 15:54b-55)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "GLORIOUS-5",
        mystery_code: "GLORIOUS",
        image: "glorious-detail-5.jpg",
        title: "The Fifth Glorious Mystery",
        subtitle: "The Coronation of Mary as Queen of Heaven and Earth",
        detail_1: "1. From ivory palaces stringed instruments make you glad; daughters of kings are among your ladies of honor; at your right hand stands the queen in gold of Ophir. (Psalm 95:8b-9, RSV)",
        detail_2: "2. A great sign appeared in the sky, a woman clothed with the sun, with the moon under her feet, and on her head a crown of twelve stars. (Revelation 12:1)",
        detail_3: "3. When the dragon saw that it had been thrown down to the earth, it pursued the woman who had given birth to the male child. (Revelation 12:13)",
        detail_4: "4. But the woman was given the two wings of the great eagle, so that she could fly to her place in the desert, where, far from the serpent, she was taken care of for a year, two years, and a half-year. (Revelation 12:14)",
        detail_5: "5. The serpent, however, spewed a torrent of water out of his mouth after the woman to sweep her away with the current. (Revelation 12:15)",
        detail_6: "6. But the earth helped the woman and opened its mouth and swallowed the flood that the dragon spewed out of its mouth. (Revelation 12:16)",
        detail_7: "7. Then the dragon became angry with the woman and went off to wage war against the rest of her offspring, those who keep God’s commandments and bear witness to Jesus. (Revelation 12:17)",
        detail_8: "8. “Most blessed are you among women, and blessed is the fruit of your womb. And how does this happen to me, that the mother of my Lord should come to me?” (Luke 1:42b-43)",
        detail_9: "9. “My soul proclaims the greatness of the Lord; my spirit rejoices in God my savior. For he has looked upon his handmaid’s lowliness; behold, from now on will all ages call me blessed. (Luke 1:46b-48)",
        detail_10: "10. “He has thrown down the rulers from their thrones but lifted up the lowly.” (Luke 1:52)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-1",
        mystery_code: "JOYFUL",
        image: "joyful-detail-1.jpg",
        title: "The First Joyful Mystery",
        subtitle: "The Annunication",
        detail_1: "1. In the sixth month, the angel Gabriel was sent from God to a town of Galilee called Nazareth, to a virgin betrothed to a man named Joseph, of the house of David, and the virgin’s name was Mary. (Luke 1:26-27)",
        detail_2: "2. And coming to her, he said, “Hail, favored one! The Lord is with you.” (Luke 1:28)",
        detail_3: "3. But she was greatly troubled at what was said and pondered what sort of greeting this might be. Then the angel said to her, “Do not be afraid, Mary, for you have found favor with God.” (Luke 1:29-30)",
        detail_4: "4. “Behold, you will conceive in your womb and bear a son, and you shall name him Jesus.” (Luke 1:31)",
        detail_5: "5. “He will be great and will be called Son of the Most High, and the Lord God will give him the throne of David his father, and he will rule over the house of Jacob forever, and of his kingdom there will be no end.” (Luke 1:32-33)",
        detail_6: "6. But Mary said to the angel, “How can this be, since I have no relations with a man?” (Luke 1:34)",
        detail_7: "7. And the angel said to her in reply, “The holy Spirit will come upon you, and the power of the Most High will overshadow you. Therefore the child to be born will be called holy, the Son of God.” (Luke 1:35)",
        detail_8: "8. “And behold, Elizabeth, your relative, has also conceived a son in her old age, and this is the sixth month for her who was called barren; for nothing will be impossible for God.” (Luke 1:36-37)",
        detail_9: "9. Mary said, “Behold, I am the handmaid of the Lord. May it be done to me according to your word.” Then the angel departed from her. (Luke 1:38)",
        detail_10: "10. And the Word became flesh and made his dwelling among us, and we saw his glory, the glory as of the Father’s only Son, full of grace and truth. (John 1:14)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-2",
        mystery_code: "JOYFUL",
        image: "joyful-detail-2.jpg",
        title: "The Second Joyful Mystery",
        subtitle: "The Visitation",
        detail_1: "1. During those days Mary set out and traveled to the hill country in haste to a town of Judah, where she entered the house of Zechariah and greeted Elizabeth. (Luke 1:39-40)",
        detail_2: "2. When Elizabeth heard Mary’s greeting, the infant leaped in her womb, and Elizabeth, filled with the holy Spirit, cried out in a loud voice and said, “Most blessed are you among women, and blessed is the fruit of your womb.” (Luke 1:41-42)",
        detail_3: "3. “And how does this happen to me, that the mother of my Lord should come to me? For at the moment the sound of your greeting reached my ears, the infant in my womb leaped for joy.” (Luke 1:43-44)",
        detail_4: "4. Blessed are you who believed that what was spoken to you by the Lord would be fulfilled.” (Luke 1:45)",
        detail_5: "5. And Mary said: “My soul proclaims the greatness of the Lord; my spirit rejoices in God my savior.” (Luke 1:46-47)",
        detail_6: "6. “For he has looked upon his handmaid’s lowliness; behold, from now on will all ages call me blessed.” (Luke 1:48)",
        detail_7: "7. “The Mighty One has done great things for me, and holy is his name. His mercy is from age to age to those who fear him.” (Luke 1:49-50)",
        detail_8: "8. “He has shown might with his arm, dispersed the arrogant of mind and heart. He has thrown down the rulers from their thrones but lifted up the lowly.” (Luke 1:51-52)",
        detail_9: "9. “The hungry he has filled with good things; the rich he has sent away empty. He has helped Israel his servant, remembering his mercy, according to his promise to our fathers, to Abraham and to his descendants forever.” (Luke 1:53-55)",
        detail_10: "10. Mary remained with her about three months and then returned to her home. (Luke 1:56)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-3",
        mystery_code: "JOYFUL",
        image: "joyful-detail-3.jpg",
        title: "The Third Joyful Mystery",
        subtitle: "The Nativity",
        detail_1: "1. Now this is how the birth of Jesus Christ came about. When his mother Mary was betrothed to Joseph, but before they lived together, she was found with child through the holy Spirit. (Matthew 1:18)",
        detail_2: "2. Joseph her husband, since he was a righteous man, yet unwilling to expose her to shame, decided to divorce her quietly. (Matthew 1:19)",
        detail_3: "3. Such was his intention when, behold, the angel of the Lord appeared to him in a dream and said, “Joseph, son of David, do not be afraid to take Mary your wife into your home. For it is through the holy Spirit that this child has been conceived in her. She will bear a son and you are to name him Jesus, because he will save his people from their sins.” (Matthew 1:20-21)",
        detail_4: "4. In those days a decree went out from Caesar Augustus that the whole world should be enrolled. So all went to be enrolled, each to his own town. And Joseph too went up from Galilee from the town of Nazareth to Judea, to the city of David that is called Bethlehem, because he was of the house and family of David, to be enrolled with Mary, his betrothed, who was with child. (Luke 2:1, 3-5)",
        detail_5: "5. While they were there, the time came for her to have her child, and she gave birth to her firstborn son. She wrapped him in swaddling clothes and laid him in a manger, because there was no room for them in the inn. (Luke 2:6-7)",
        detail_6: "6. Now there were shepherds in that region living in the fields and keeping the night watch over their flock. The angel of the Lord appeared to them and the glory of the Lord shone around them, and they were struck with great fear. (Luke 2:8-9)",
        detail_7: "7. The angel said to them, “Do not be afraid; for behold, I proclaim to you good news of great joy that will be for all the people. (Luke 2:10)",
        detail_8: "8. For today in the city of David a savior has been born for you who is Messiah and Lord. (Luke 2:11)",
        detail_9: "9. And this will be a sign for you: you will find an infant wrapped in swaddling clothes and lying in a manger.” (Luke 2:12)",
        detail_10: "10. And suddenly there was a multitude of the heavenly host with the angel, praising God and saying:  “Glory to God in the highest and on earth peace to those on whom his favor rests.” (Luke 2:13-14)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-4",
        mystery_code: "JOYFUL",
        image: "joyful-detail-4.jpg",
        title: "The Fourth Joyful Mystery",
        subtitle: "The Presentation",
        detail_1: "1. When the days were completed for their purification according to the law of Moses, they took him up to Jerusalem to present him to the Lord. (Luke 2:22)",
        detail_2: "2. Now there was a man in Jerusalem whose name was Simeon. This man was righteous and devout, awaiting the consolation of Israel, and the holy Spirit was upon him. (Luke 2:25)",
        detail_3: "3. It had been revealed to him by the holy Spirit that he should not see death before he had seen the Messiah of the Lord. (Luke 2:26)",
        detail_4: "4. He came in the Spirit into the temple; and when the parents brought in the child Jesus to perform the custom of the law in regard to him, he took him into his arms and blessed God. (Luke 2:27-28a) ",
        detail_5: "5. “Now, Master, you may let your servant go in peace, according to your word,” (Luke 2:29)",
        detail_6: "6. “For my eyes have seen your salvation, which you prepared in sight of all the peoples,” (Luke 2:30-31)",
        detail_7: "7. “A light for revelation to the Gentiles, and glory for your people Israel.” (Luke 2:32)",
        detail_8: "8. The child’s father and mother were amazed at what was said about him; and Simeon blessed them and said to Mary his mother, “Behold, this child is destined for the fall and rise of many in Israel, and to be a sign that will be contradicted (and you yourself a sword will pierce) so that the thoughts of many hearts may be revealed.” (Luke 2:33-35)",
        detail_9: "9. There was also a prophetess, Anna, the daughter of Phanuel, of the tribe of Asher. She was advanced in years, having lived seven years with her husband after her marriage, and then as a widow until she was eighty-four. She never left the temple, but worshiped night and day with fasting and prayer. (Luke 2:36-37)",
        detail_10: "10. And coming forward at that very time, she gave thanks to God and spoke about the child to all who were awaiting the redemption of Jerusalem. (Luke 2:38)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "JOYFUL-5",
        mystery_code: "JOYFUL",
        image: "joyful-detail-5.jpg",
        title: "The Fifth Joyful Mystery",
        subtitle: "The Finding in the Temple",
        detail_1: "1. Each year his parents went to Jerusalem for the feast of Passover, and when he was twelve years old, they went up according to festival custom. (Luke 2:41-42)",
        detail_2: "2. After they had completed its days, as they were returning, the boy Jesus remained behind in Jerusalem, but his parents did not know it. (Luke 2:43)",
        detail_3: "3. Thinking that he was in the caravan, they journeyed for a day and looked for him among their relatives and acquaintances. (Luke 2:44)",
        detail_4: "4. But not finding him, they returned to Jerusalem to look for him. (Luke 2:45)",
        detail_5: "5. After three days they found him in the temple, sitting in the midst of the teachers, listening to them and asking them questions. (Luke 2:46)",
        detail_6: "6. And all who heard him were astounded at his understanding and his answers. (Luke 2:47)",
        detail_7: "7. When his parents saw him, they were astonished, and his mother said to him, “Son, why have you done this to us? Your father and I have been looking for you with great anxiety.” (Luke 2:48)",
        detail_8: "8. And he said to them, “Why were you looking for me? Did you not know that I must be in my Father’s house?” But they did not understand what he said to them. (Luke 2:49-50)",
        detail_9: "9. He went down with them and came to Nazareth, and was obedient to them; and his mother kept all these things in her heart. (Luke 2:51)",
        detail_10: "10. And Jesus advanced in wisdom and age and favor before God and man. (Luke 2:52)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "SORROWFUL-1",
        mystery_code: "SORROWFUL",
        image: "sorrowful-detail-1.jpg",
        title: "The First Sorrowful Mystery",
        subtitle: "The Agony in the Garden",
        detail_1: "1. Then Jesus came with them to a place called Gethsemane, and he said to his disciples, “Sit here while I go over there and pray.” He took along Peter and the two sons of Zebedee, and began to feel sorrow and distress. (Matthew 26:36-37)",
        detail_2: "2. Then he said to them, “My soul is sorrowful even to death. Remain here and keep watch with me.” (Matthew 26:38)",
        detail_3: "3. He advanced a little and fell to the ground and prayed that if it were possible the hour might pass by him; he said, “Abba, Father, all things are possible to you. Take this cup away from me, but not what I will but what you will.” (Mark 14:35-36)",
        detail_4: "4. When he returned to his disciples he found them asleep. He said to Peter, “So you could not keep watch with me for one hour? Watch and pray that you may not undergo the test. The spirit is willing, but the flesh is weak.” (Matthew 26:40-41)",
        detail_5: "5. Withdrawing a second time, he prayed again, “My Father, if it is not possible that this cup pass without my drinking it, your will be done!” (Matthew 26:42)",
        detail_6: "6. Then he returned once more and found them asleep, for they could not keep their eyes open. He left them and withdrew again and prayed a third time, saying the same thing again. (Matthew 26:43-44)",
        detail_7: "7. He was in such agony and he prayed so fervently that his sweat became like drops of blood falling on the ground. (Luke 22:44)",
        detail_8: "8. When he rose from prayer and returned to his disciples, he found them sleeping from grief. He said to them, “Why are you sleeping? Get up and pray that you may not undergo the test.” (Luke 22:45-46)",
        detail_9: "9. While he was still speaking, a crowd approached and in front was one of the Twelve, a man named Judas. He went up to Jesus to kiss him. Jesus said to him, “Judas, are you betraying the Son of Man with a kiss?” (Luke 22:47-48)",
        detail_10: "10. At this they laid hands on him and arrested him. (Mark 14:46)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "SORROWFUL-2",
        mystery_code: "SORROWFUL",
        image: "sorrowful-detail-2.jpg",
        title: "The Second Sorrowful Mystery",
        subtitle: "The Scourging at the Pillar",
        detail_1: "1. When it was morning, all the chief priests and the elders of the people took counsel against Jesus to put him to death. They bound him, led him away, and handed him over to Pilate, the governor. (Matthew 27:1-2)",
        detail_2: "2. So Pilate went back into the praetorium and summoned Jesus and said to him, “Are you the King of the Jews?” (John 18:33)",
        detail_3: "3. Jesus answered, “Do you say this on your own or have others told you about me?” Pilate answered, “I am not a Jew, am I? Your own nation and the chief priests handed you over to me. What have you done?” (John 18:34-35)",
        detail_4: "4. Jesus answered, “My kingdom does not belong to this world. If my kingdom did belong to this world, my attendants would be fighting to keep me from being handed over to the Jews. But as it is, my kingdom is not here.” (John 18:36)",
        detail_5: "5. Now on the occasion of the feast he used to release to them one prisoner whom they requested. A man called Barabbas was then in prison along with the rebels who had committed murder in a rebellion. (Mark 15:6-7)",
        detail_6: "6. The chief priests and the elders persuaded the crowds to ask for Barabbas but to destroy Jesus. The governor said to them in reply, “Which of the two do you want me to release to you?” They answered, “Barabbas!” (Matthew 27:20-21)",
        detail_7: "7. Pilate said to them, “Then what shall I do with Jesus called Messiah?” They all said, “Let him be crucified!” (Matthew 27:22)",
        detail_8: "8. So Pilate, wishing to satisfy the crowd, released Barabbas to them and, after he had Jesus scourged, handed him over to be crucified. (Mark 15:15)",
        detail_9: "9. Yet it was our pain that he bore, our sufferings he endured. We thought of him as stricken, struck down by God and afflicted. (Isaiah 53:4)",
        detail_10: "10. But he was pierced for our sins, crushed for our iniquity. He bore the punishment that makes us whole, by his wounds we were healed. (Isaiah 53:5)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "SORROWFUL-3",
        mystery_code: "SORROWFUL",
        image: "sorrowful-detail-3.jpg",
        title: "The Third Sorrowful Mystery",
        subtitle: "The Crowning with Thorns",
        detail_1: "1. Then the soldiers of the governor took Jesus inside the praetorium and gathered the whole cohort around him. (Matthew 27:27)",
        detail_2: "2. They stripped off his clothes and threw a scarlet military cloak about him. (Matthew 27:28)",
        detail_3: "3. Weaving a crown out of thorns, they placed it on his head, and a reed in his right hand. And kneeling before him, they mocked him, saying, “Hail, King of the Jews!” (Matthew 27:29)",
        detail_4: "4. They spat upon him and took the reed and kept striking him on the head. (Matthew 27:30)",
        detail_5: "5. Once more Pilate went out and said to them, “Look, I am bringing him out to you, so that you may know that I find no guilt in him.” So Jesus came out, wearing the crown of thorns and the purple cloak. And he said to them, “Behold, the man!”  (John 19:4-5)",
        detail_6: "6. And when they had mocked him, they stripped him of the purple cloak, dressed him in his own clothes, and led him out to crucify him. (Mark 15:20)",
        detail_7: "7. He was spurned and avoided by men, a man of suffering, knowing pain, Like one from whom you turn your face, spurned, and we held him in no esteem. (Isaiah 53:3)",
        detail_8: "8. We had all gone astray like sheep, all following our own way; But the LORD laid upon him the guilt of us all. (Isaiah 53:6)",
        detail_9: "9. Though harshly treated, he submitted and did not open his mouth; Like a lamb led to slaughter or a sheep silent before shearers, he did not open his mouth. (Isaiah 53:7)",
        detail_10: "10. But it was the LORD’s will to crush him with pain. By making his life as a reparation offering, he shall see his offspring, shall lengthen his days, and the LORD’s will shall be accomplished through him. (Isaiah 53:10)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "SORROWFUL-4",
        mystery_code: "SORROWFUL",
        image: "sorrowful-detail-4.jpg",
        title: "The Fourth Sorrowful Mystery",
        subtitle: "The Carrying of the Cross",
        detail_1: "1. So they took Jesus, and carrying the cross himself he went out to what is called the Place of the Skull, in Hebrew, Golgotha. (John 19:16b-17)",
        detail_2: "2. As they led him away they took hold of a certain Simon, a Cyrenian, who was coming in from the country; and after laying the cross on him, they made him carry it behind Jesus. (Luke 23:26)",
        detail_3: "3. A large crowd of people followed Jesus, including many women who mourned and lamented him. (Luke 23:27)",
        detail_4: "4. Jesus turned to them and said, “Daughters of Jerusalem, do not weep for me; weep instead for yourselves and for your children, for indeed, the days are coming when people will say, ‘Blessed are the barren, the wombs that never bore and the breasts that never nursed.’” (Luke 23:28-29)",
        detail_5: "5. “At that time people will say to the mountains, ‘Fall upon us!’ and to the hills, ‘Cover us!’ for if these things are done when the wood is green what will happen when it is dry?” (Luke 23:30-31)",
        detail_6: "6. Now two others, both criminals, were led away with him to be executed. (Luke 23:32)",
        detail_7: "7. “If anyone wishes to come after me, he must deny himself and take up his cross daily and follow me.” (Luke 9:23)",
        detail_8: "8. “For whoever wishes to save his life will lose it, but whoever loses his life for my sake will save it.” (Luke 9:24)",
        detail_9: "9. “What profit is there for one to gain the whole world yet lose or forfeit himself?” (Luke 9:25)",
        detail_10: "10. Because of his anguish he shall see the light; because of his knowledge he shall be content; My servant, the just one, shall justify the many, their iniquity he shall bear. (Isaiah 53:11)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "SORROWFUL-5",
        mystery_code: "SORROWFUL",
        image: "sorrowful-detail-5.jpg",
        title: "The Fifth Sorrowful Mystery",
        subtitle: "The Crucifixion",
        detail_1: "1. When they came to the place called the Skull, they crucified him and the criminals there, one on his right, the other on his left. (Luke 23:33)",
        detail_2: "2. Then Jesus said, “Father, forgive them, they know not what they do.” (Luke 23:34a)",
        detail_3: "3. After they had crucified him, they divided his garments by casting lots; then they sat down and kept watch over him there. (Matthew 27:35-36)",
        detail_4: "4. The inscription of the charge against him read, “The King of the Jews.” (Mark 15:26)",
        detail_5: "5. Those passing by reviled him, shaking their heads and saying, “You who would destroy the temple and rebuild it in three days, save yourself, if you are the Son of God, and come down from the cross!” (Matthew 27:39-40)",
        detail_6: "6. At noon darkness came over the whole land until three in the afternoon. And at three o’clock Jesus cried out in a loud voice, “Eloi, Eloi, lema sabachthani?” which is translated, “My God, my God, why have you forsaken me?” (Mark 15:33-34)",
        detail_7: "7. When Jesus saw his mother and the disciple there whom he loved, he said to his mother, “Woman, behold, your son.” Then he said to the disciple, “Behold, your mother.” And from that hour the disciple took her into his home. (John 19:26-27)",
        detail_8: "8. After this, aware that everything was now finished, in order that the scripture might be fulfilled, Jesus said, “I thirst.” (John 19:28)",
        detail_9: "9. There was a vessel filled with common wine. So they put a sponge soaked in wine on a sprig of hyssop and put it up to his mouth. When Jesus had taken the wine, he said, “It is finished.” And bowing his head, he handed over the spirit. (John 19:29-30)",
        detail_10: "10. When the centurion who stood facing him saw how he breathed his last he said, “Truly this man was the Son of God!” (Mark 15:39)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "LUMINOUS-1",
        mystery_code: "LUMINOUS",
        image: "luminous-detail-1.jpg",
        title: "The First Luminous Mystery",
        subtitle: "The Baptism of the Lord",
        detail_1: "1. In those days John the Baptist appeared, preaching in the desert of Judea and saying, “Repent, for the kingdom of heaven is at hand!” (Matthew 3:1-2)",
        detail_2: "2. As it is written in Isaiah the prophet: “Behold, I am sending my messenger ahead of you; he will prepare your way.” (Mark 1:2)",
        detail_3: "3. At that time Jerusalem, all Judea, and the whole region around the Jordan were going out to him and were being baptized by him in the Jordan River as they acknowledged their sins. (Matthew 3:5-6)",
        detail_4: "4. “I am baptizing you with water, for repentance, but the one who is coming after me is mightier than I. I am not worthy to carry his sandals.” (Matthew 3:11a)",
        detail_5: "5. “He will baptize you with the Holy Spirit and fire.” (Matthew 3:11b)",
        detail_6: "6. It happened in those days that Jesus came from Nazareth of Galilee and was baptized in the Jordan by John. (Mark 1:9)",
        detail_7: "7. John tried to prevent him, saying, “I need to be baptized by you, and yet you are coming to me?” (Matthew 3:14)",
        detail_8: "8. Jesus said to him in reply, “Allow it now, for thus it is fitting for us to fulfill all righteousness.” Then he allowed him. (Matthew 3:15)",
        detail_9: "9. On coming up out of the water he saw the heavens being torn open and the Spirit, like a dove, descending upon him. (Mark 1:10)",
        detail_10: "10. And a voice came from the heavens, “You are my beloved Son; with you I am well pleased.” (Mark 1:11)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "LUMINOUS-2",
        mystery_code: "LUMINOUS",
        image: "luminous-detail-2.jpg",
        title: "The Second Luminous Mystery",
        subtitle: "The Wedding Feast at Cana",
        detail_1: "1. On the third day there was a wedding in Cana in Galilee, and the mother of Jesus was there. (John 2:1)",
        detail_2: "2. Jesus and his disciples were also invited to the wedding. (John 2:2)",
        detail_3: "3. When the wine ran short, the mother of Jesus said to him, “They have no wine.” (John 2:3)",
        detail_4: "4. And Jesus said to her, “Woman, how does your concern affect me? My hour has not yet come.” (John 2:4)",
        detail_5: "5. His mother said to the servers, “Do whatever he tells you.” (John 2:5) ",
        detail_6: "6. Now there were six stone water jars there for Jewish ceremonial washings, each holding twenty to thirty gallons. (John 2:6)",
        detail_7: "7. Jesus told them, “Fill the jars with water.” So they filled them to the brim. (John 2:7)",
        detail_8: "8. Then he told them, “Draw some out now and take it to the headwaiter.” So they took it. (John 2:8)",
        detail_9: "9. And when the headwaiter tasted the water that had become wine, without knowing where it came from (although the servers who had drawn the water knew), the headwaiter called the bridegroom and said to him, “Everyone serves good wine first, and then when people have drunk freely, an inferior one; but you have kept the good wine until now.” (John 2:9-10)",
        detail_10: "10. Jesus did this as the beginning of his signs in Cana in Galilee and so revealed his glory, and his disciples began to believe in him. (John 2:11)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "LUMINOUS-3",
        mystery_code: "LUMINOUS",
        image: "luminous-detail-3.jpg",
        title: "The Third Luminous Mystery",
        subtitle: "The Proclamation of the Kingdom",
        detail_1: "1. “Repent, for the kingdom of heaven is at hand.” (Matthew 4:17b)",
        detail_2: "2. “Blessed are the poor in spirit, for theirs is the kingdom of heaven.” (Matthew 5:3)",
        detail_3: "3. “Blessed are they who are persecuted for the sake of righteousness, for theirs is the kingdom of heaven.” (Matthew 5:10)",
        detail_4: "4. “What is the kingdom of God like? To what can I compare it? It is like a mustard seed that a person took and planted in the garden. When it was fully grown, it became a large bush and ‘the birds of the sky dwelt in its branches.” (Luke 13:18-19)",
        detail_5: "5. “The kingdom of heaven is like a treasure buried in a field, which a person finds and hides again, and out of joy goes and sells all that he has and buys that field.” (Matthew 13:44)",
        detail_6: "6. “I tell you, unless your righteousness surpasses that of the scribes and Pharisees, you will not enter into the kingdom of heaven.” (Matthew 5:20)",
        detail_7: "7. “So do not worry and say, ‘What are we to eat?’ or ‘What are we to drink?’ or ‘What are we to wear?’ All these things the pagans seek. Your heavenly Father knows that you need them all. But seek first the kingdom of God and his righteousness, and all these things will be given you besides.” (Matthew 6:31-33)",
        detail_8: "8. “Amen, I say to you, whoever does not accept the kingdom of God like a child will not enter it.” (Mark 10:15)",
        detail_9: "9. “My kingdom does not belong to this world. If my kingdom did belong to this world, my attendants would be fighting to keep me from being handed over to the Jews. But as it is, my kingdom is not here.” (John 18:36)",
        detail_10: "10. He delivered us from the power of darkness and transferred us to the kingdom of his beloved Son, in  whom we have redemption, the forgiveness of sins. (Colossians 1:13-14)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "LUMINOUS-4",
        mystery_code: "LUMINOUS",
        image: "luminous-detail-4.jpg",
        title: "The Fourth Luminous Mystery",
        subtitle: "The Transfiguration",
        detail_1: "1. After six days Jesus took Peter, James, and John his brother, and led them up a high mountain by themselves. (Matthew 17:1)",
        detail_2: "2. And he was transfigured before them; his face shone like the sun and his clothes became white as light. (Matthew 17:2)",
        detail_3: "3. And behold, Moses and Elijah appeared to them, conversing with him. (Matthew 17:3)",
        detail_4: "4. Then Peter said to Jesus in reply, “Rabbi, it is good that we are here! Let us make three tents: one for you, one for Moses, and one for Elijah.” (Mark 9:5)",
        detail_5: "5. He hardly knew what to say, they were so terrified. (Mark 9:6)",
        detail_6: "6. While he was still speaking, a cloud came and cast a shadow over them, and they became frightened when they entered the cloud. (Luke 9:34)",
        detail_7: "7. Then from the cloud came a voice that said, “This is my chosen Son; listen to him.” (Luke 9:35)",
        detail_8: "8. When the disciples heard this, they fell prostrate and were very much afraid. (Matthew 17:6)",
        detail_9: "9. But Jesus came and touched them, saying, “Rise, and do not be afraid.” (Matthew 17:7)",
        detail_10: "10. And when the disciples raised their eyes, they saw no one else but Jesus alone. (Matthew 17:8)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    },
    {
        code: "LUMINOUS-5",
        mystery_code: "LUMINOUS",
        image: "luminous-detail-5.jpg",
        title: "The Fifth Luminous Mystery",
        subtitle: "The Institution of the Eucharist",
        detail_1: "1. “I am the bread of life. Your ancestors ate the manna in the desert, but they died; this is the bread that comes down from heaven so that one may eat it and not die.” (John 6:48-50)",
        detail_2: "2. “I am the living bread that came down from heaven; whoever eats this bread will live forever; and the bread that I will give is my flesh for the life of the world.” (John 6:51)",
        detail_3: "3. “Whoever eats my flesh and drinks my blood has eternal life, and I will raise him on the last day.” (John 6:54)",
        detail_4: "4. “Just as the living Father sent me and I have life because of the Father, so also the one who feeds on me will have life because of me.” (John 6:57)",
        detail_5: "5. When the day of the feast of Unleavened Bread arrived, the day for sacrificing the Passover lamb, he sent out Peter and John, instructing them, “Go and make preparations for us to eat the Passover.” (Luke 22:7-8)",
        detail_6: "6. When the hour came, he took his place at table with the apostles. He said to them, “I have eagerly desired to eat this Passover with you before I suffer, for, I tell you, I shall not eat it again until there is fulfillment in the kingdom of God.” (Luke 22:14-16)",
        detail_7: "7. While they were eating, Jesus took bread, said the blessing, broke it, and giving it to his disciples said, “Take and eat; this is my body.” (Matthew 26:26)",
        detail_8: "8. Then he took a cup, gave thanks, and gave it to them, saying, “Drink from it, all of you, for this is my blood of the covenant, which will be shed on behalf of many for the forgiveness of sins.” (Matthew 26:27-28)",
        detail_9: "9. Then, after singing a hymn, they went out to the Mount of Olives. (Mark 14:26)",
        detail_10: "10. For as often as you eat this bread and drink the cup, you proclaim the death of the Lord until he comes. (1 Corinthians 11:26)",
        created_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS")),
        updated_at: moment().format(("YYYY-MM-DD HH.mm.SS.SSS"))
    }
]
